_format_version: "3.0"
services:
  # 1. Joke API Service
  - name: joke-service
    url: http://10.0.1.11:4000
    routes:
      - name: joke-route
        paths:
          - /joke-api
        strip_path: true
        protocols: ["https"]
        https_redirect_status_code: 301
    plugins:
      - name: rate-limiting
        config:
          minute: 8  
          policy: local
          hide_client_headers: false 

  # 2. Submit Microservice
  - name: submit-service
    url: http://10.1.1.11:4200
    routes:
      - name: submit-route
        paths:
          - /submit-api
        strip_path: true
        protocols: ["https"]
        https_redirect_status_code: 301

  # 3. Moderate Microservice
  - name: moderate-service
    url: http://10.1.1.12:4300
    routes:
      - name: moderate-route
        paths:
          - /moderate-api
        strip_path: true
        protocols: ["https"]
        https_redirect_status_code: 301