services:
  mysql:
    image: mysql:8.0
    container_name: jokes_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jokes_db
    ports:
      - "3306:3306"
    volumes:
      - ./infra/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    profiles:
      - mysql

  mongo:
    image: mongo:latest
    container_name: jokes_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./infra/db-init/init.js:/docker-entrypoint-initdb.d/init.js
      - mongo_data:/data/dbn
    profiles:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jokes_rabbitmq
    ports:
      - "5672:5672"   # Message broker port
      - "15672:15672" # Management UI port

  joke-api:
    build: ./services/joke-api
    container_name: joke_api
    ports:
      - "3001:3001"
    environment:
      - DB_TYPE=${DB_TYPE:-MYSQL}
      - DB_HOST=jokes_mysql
      - MONGO_URI=mongodb://jokes_mongo:27017

  joke-etl:
    build: ./services/joke-etl
    container_name: joke_etl
    environment:
      - DB_TYPE=${DB_TYPE:-MYSQL}
      - DB_HOST=jokes_mysql
      - MONGO_URI=mongodb://jokes_mongo:27017
      - RABBITMQ_URL=amqp://jokes_rabbitmq
    depends_on:
      - rabbitmq

  submit-app:
    build: ./services/submit
    container_name: submit_app
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://jokes_rabbitmq
    volumes:
      - submit_cache:/usr/src/app/cache
    depends_on:
      - rabbitmq

  moderate-app:
    build: ./services/moderate
    container_name: moderate_app
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_URL=amqp://jokes_rabbitmq
    volumes:
      - moderate_cache:/usr/src/app/cache
    depends_on:
      - rabbitmq

volumes:
  mysql_data:
  mongo_data:
  submit_cache:
  moderate_cache: