services:
  mysql:
    image: mysql:8.0
    container_name: joke-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jokes_db
    ports:
      - "3306:3306"
    volumes:
      - ./infra/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    profiles:
      - mysql

  mongo:
    image: mongo:latest
    container_name: joke-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./infra/db-init/init.js:/docker-entrypoint-initdb.d/init.js
      - mongo-data:/data/db
    profiles:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: joke-queue
    ports:
      - "5672:5672"   
      - "15672:15672" 

  joke-api:
    build: ./services/joke-api
    container_name: joke-api
    restart: always
    # ports:
    #   - "3001:3001"
    environment:
      - DB_TYPE=MYSQL
      - DB_HOST=joke-mysql
      - MONGO_URI=mongodb://joke-mongo:27017

  joke-etl:
    build: ./services/joke-etl
    container_name: joke-etl
    restart: always
    environment:
      - DB_TYPE=MYSQL
      - DB_HOST=joke-mysql
      - MONGO_URI=mongodb://joke-mongo:27017
      - RABBITMQ_URL=amqp://joke-queue
    depends_on:
      - rabbitmq

  joke-submit:
    build: ./services/submit
    container_name: joke-submit
    # ports:
    #   - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://joke-queue
    volumes:
      - submit-cache:/usr/src/app/cache
    depends_on:
      - rabbitmq

  joke-moderate:
    build: ./services/moderate
    container_name: joke-moderate
    # ports:
    #   - "3003:3003"
    environment:
      - RABBITMQ_URL=amqp://joke-queue
      - AUTH0_BASE_URL=http://localhost:8000/moderate-api
      # In production, this would be AUTH0_BASE_URL=http://20.205.40.175/moderate-api
    volumes:
      - moderate-cache:/usr/src/app/cache
    depends_on:
      - rabbitmq

  api-gateway:
    image: kong:latest 
    container_name: joke-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./infra/api-gateway/kong.yaml:/kong/declarative/kong.yaml
    depends_on:
      - joke-api
      - joke-submit
      - joke-moderate

volumes:
  mysql-data:
  mongo-data:
  submit-cache:
  moderate-cache: