services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - joke-network
networks:
  joke-network:
    driver: bridge