services:
  kong:
    image: kong:latest
    container_name: kong_gateway
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_LISTEN: 0.0.0.0:80, 0.0.0.0:443 ssl
      KONG_SSL_CERT: /certs/live/gateway/fullchain.pem
      KONG_SSL_CERT_KEY: /certs/live/gateway/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./kong.yaml:/kong/declarative/kong.yaml
      - /etc/letsencrypt:/certs:ro
    networks:
      - joke-network
networks:
  joke-network:
    driver: bridge
