services:
  moderate-app:
    image: ghcr.io/lehan2512/moderate-app:latest
    restart: unless-stopped
    ports: ["4300:3300"]
    environment:
      - PORT=3300
      - RABBITMQ_URL=amqp://10.1.1.10
      - AUTH0_BASE_URL=https://lehan-joke.eastasia.cloudapp.azure.com/moderate-api
      - AUTH0_CLIENT_ID=w7DnLzgXwsOG8XgORbCVHH3LhGIMMsc6
      - AUTH0_CLIENT_SECRET=-QqchSKaUvkCRDsKqzoW7-9gXP8VZ-KyY3UAWTs6nxl2YzoGv55Qk53Xe71oQp3w
    volumes:
      - moderate_cache:/usr/src/app/cache
    networks:
      - joke-network
volumes:
  moderate_cache:
networks:
  joke-network:
    driver: bridge
