services:
  submit-app:
    image: ghcr.io/lehan2512/submit-app:latest
    restart: unless-stopped
    ports: ["3002:3002"]
    environment:
      - RABBITMQ_URL=amqp://10.1.1.10
    volumes:
      - submit_cache:/usr/src/app/cache
    networks:
      - joke-network
volumes:
  submit_cache:
networks:
  joke-network:
    driver: bridge
